name: Node CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        bash build.sh --name=AwesomeProject --type=1
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
