name: Web Build + Test

on:
  schedule:
    - cron:  '0 0 * * MON'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Commit Message
      run: |
        echo "::set-env name=COMMIT_MESSAGE::$(git log -1 --pretty=format:%s)"
    - name: Build a fresh React App
      run: |
        bash build.sh --name=ReactStarterKit --type=1
    - name: Lint
      run: |
        ./node_modules/.bin/eslint "src/**/*.js"
    - name: Jest Tests
      run: |
        yarn test
      env:
        CI: true
    - name: Commit files to React Starter Kit repo
      run: |
        rm -rf .git
        git clone https://github.com/mcnamee/react-starter-kit.git TEMP
        mv TEMP/.git .git
        rm -rf TEMP
        git config --local user.email "${{ secrets.GH_EMAIL }}"
        git config --local user.name "mcnamee/react-native-boilerplate-builder"
        git add -A
        git commit -m "$COMMIT_MESSAGE (RNBB Bot)" -a
    - name: Push files to React Starter Kit repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: mcnamee/react-starter-kit
        branch: master
