name: Web Build + Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build a fresh React App
      run: |
        bash build.sh --name=ReactStarterKit --type=1
    - name: Lint
      run: |
        ./node_modules/.bin/eslint "src/**/*.js"
    - name: Jest Tests
      run: |
        yarn test
      env:
        CI: true
    - name: Commit files to React Starter Kit repo
      run: |
        git config --local user.email "matt@mcnamee.co"
        git config --local user.name "mcnamee/react-native-boilerplate-builder"
        git add -A
        git commit -m "Automated updates (mcnamee/react-native-boilerplate-builder)" -a
    - name: Push files to React Starter Kit repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: mcnamee/react-starter-test
        branch: master
        force: true
